spring:
  application:
    name: 'CaptureAnything'

  data:
    mongodb:
      uri: mongodb+srv://pahulronaldo:3Yp4FWkMsEwRKHp3@captureanything.sb5mp.mongodb.net/captureanythingdb?retryWrites=true&w=majority&appName=CaptureAnything

management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # or "*" to expose all endpoints
      base-path: "/actuator"

  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true


  security:
    enabled: false




mongodb+srv://pahulronaldo:3Yp4FWkMsEwRKHp3@captureanything:
  sb5mp:
    mongodb:
      net/?retryWrites=true&w=majority&appName=CaptureAnything: