spring:
  profiles:
    active: local
  application:
    name: 'CaptureAnything'
  security:
    enabled: false
  data:
    mongodb:
      uri: mongodb+srv://pahulronaldo:3Yp4FWkMsEwRKHp3@captureanything.sb5mp.mongodb.net/captureanythingdb?retryWrites=true&w=majority&appName=CaptureAnything
management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # or "*" to expose all endpoints
      base-path: "/actuator"

  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true





weather:
  consumer:
    groupId: weather-consumer-group
  producer:
    topic: weather-now
